FROM ft-rails:on-build

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]

# docker build -f ft-rails/Dockerfile -t ft-rails:on-build .
# docker build -t ex02 .
# docker run -it --name ft-rails -p 3000:3000 ex02